Constant_3DEBuyer = 'Buyer'
Constant_Company_Info = 'Company Info'
Constant_Buyer_Info = 'Buyer Info'
Constant_Description = 'Description of Goods'
Constant_Items= "Items"
Constant_cid299 = '(cid:299)'
Constant_u2122  ='\u2122'
Constant_SL_No = "Sl No."
Constant_Sl = "Sl"
Constant_Amount_Charageable ="Amount Chargeable (in words)"
Constant_Tax_Amount_words = "Tax Amount (in words)"
constant_Authorised_Signatory = "Authorised Signatory"
Constant_HSN_SAC = "HSN/SAC"
Constant_Declaration = "Declaration for"
Constant_Tax_value = "Taxable Value"
Constant_integrated_tax = "Integrated Tax"
Constant_Total_tax_amt = "Total Tax Amount"
Constant_BankName = "Bank Name"
Constant_Branch_IFS = "Branch & IFS Code"
COnstant_Account_no = "A/c No."
Constant_Declaration = "Declaration"